### ISSUE TITLE
Add theme to WordPress.org theme directory

### ISSUE THREAD

**Issue by michaelenger** [wp960/Wordpress-960#6]
The theme is coming together as a nice starter theme, so maybe it's time to tag the current version and upload it to the [WordPress.org theme directory](http://wordpress.org/extend/themes/), so it's discoverable.

**Comment by Roach** [comment]
I agree, that would be awesome

**Comment by Roach** [comment]
Does it meet the requirements? http://codex.wordpress.org/Theme_Review
